language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --no-progress --prefer-source

script:
  - vendor/bin/php-cs-fixer fix --dry-run --diff  --config=.php_cs.dist
  - vendor/bin/phpunit --coverage-text --coverage-clover=clover.xml

after_success:
  - vendor/bin/php-coveralls -x clover.xml -o coveralls-upload.json