name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    name: Test PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.2', '7.3', '7.4']

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          # php-version: '7.2'
          extensions: curl, mbstring, intl, libxml, simplexml
          coverage: xdebug
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: Get composer cache directory
        id: composer-cache-dir
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache Composer packages
        id: composer-cache-restore
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache-dir.outputs.dir }}
          # path: vendor
          key: ${{ runner.os }}-node-${{ hashFiles('**/composer.json') }}
          # key: node-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            composer-${{ matrix.php-versions }}
#          restore-keys: |
#              composer-7.2
      - name: Install dependencies
        run: (test -d vendor && echo vendor directory exists) || composer install --prefer-dist --no-progress --no-suggest
      - name: Run PHPUnit
        run: vendor/bin/phpunit --coverage-text --coverage-clover clover.xml
      - name: "[Coveralls] Extract branch name"
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: "[Coveralls] Checkout branch"
        shell: bash
        run: git fetch && git checkout ${{ steps.extract_branch.outputs.branch }}
      - name: "[Coveralls] Send report"
        run: vendor/bin/php-coveralls -v -x clover.xml -o coveralls-upload.json
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
